### ISSUE TITLE
Message box doesn't have the same color

### ISSUE THREAD

**Issue by Wittyy** [AlexFlipnote/Discord_Theme#116]
For some reason, the message box doesn't seem to have the darker color. How it currently looks: https://i.imgur.com/9HygWQR.png

**Comment by AlexFlipnote** [comment]
This has already been resolved yesterday with the latest Discord Canary in bb38051
Keep in mind if you use Discord Stable, these kind of bugs are not unusual to encounter, as this theme's goal is to stay up-to-date with the latest and has to get old CSS code removed in order to comply with the latest.

![Image](https://i.alexflipnote.xyz/68d464.png)

**Comment by Wittyy** [comment]
Alright, I'll make the switch back to Canary then. Thanks.
